# Generated by Django 4.2.6 on 2023-12-04 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=32, null=True, verbose_name='商品名')),
                ('commentname', models.CharField(blank=True, max_length=32, null=True, verbose_name='评论者名字')),
                ('article', models.CharField(blank=True, max_length=32, null=True, verbose_name='评论内容')),
            ],
        ),
        migrations.CreateModel(
            name='goods_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=32, null=True, verbose_name='商品名')),
                ('category', models.CharField(blank=True, max_length=32, null=True, verbose_name='商品类别')),
                ('price', models.CharField(blank=True, max_length=32, null=True, verbose_name='价格')),
                ('introduction', models.CharField(blank=True, max_length=32, null=True, verbose_name='商品介绍')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='pictures/')),
            ],
        ),
        migrations.CreateModel(
            name='price_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=32, null=True, verbose_name='商品名')),
                ('pidname', models.CharField(blank=True, max_length=32, null=True, verbose_name='出价者名字')),
                ('price', models.CharField(blank=True, max_length=32, null=True, verbose_name='价格')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=32, null=True, verbose_name='姓名')),
                ('password', models.CharField(blank=True, max_length=32, null=True, verbose_name='密码')),
            ],
        ),
    ]
