# Generated by Django 4.2.6 on 2023-12-04 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods_list',
            name='publisher',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='发布者'),
        ),
        migrations.AddField(
            model_name='users',
            name='watch',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='监视名单'),
        ),
    ]
